server:
  port: 9090
spring:
  profiles:
    active: local

---
spring:
  profiles: local
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/toyProjectDB?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

---
spring:
  profiles: alpha
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/toyProjectDB?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
