server:
  port: 9090
  shutdown: graceful

spring:
  lifecycle:
    timeout-per-shutdown-phase: 30s
  profiles:
    active: local
    group:
      "local": "console-logging"
      "dev" : "console-logging, file-info-logging, file-error-logging"

  jpa:
    hibernate:
      ddl-auto: validate
