spring:
  config:
    activate:
      on-profile: dev

  output:
    ansi:
      enabled: always

  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/my-async-test?serverTimezone=UTC&characterEncoding=UTF-8&rewriteBatchedStatements=true
      username: root
      password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.batch_size: 50
        format_sql: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    show-sql: true

logging:
  level:
    org:
      hibernate:
        type: TRACE
