spring:
  output:
    ansi:
      enabled: always

  datasource:
    first-database:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/first-database?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

    second-database:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/second-database?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

  # JPA
  jpa:
    hibernate:
      ddl-auto: create
      second.ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type: trace
